[book]
authors = ["robopandas"]
language = "en"
multilingual = false
src = "src"
title = "The Cookbook"

[preprocessor.blame]
source = "https://github.com/dr-hextanium/cookbook/commit/"

[output.html.code.hidelines]
java = "# "
kt = "# "

[output.html]
mathjax-support = true
site-url = "/cookbook/"
git-repository-url = "https://github.com/dr-hextanium/cookbook/tree/main"
edit-url-template = "https://github.com/dr-hextanium/cookbook/tree/main/{path}"

[output.html.redirect]
"/help.html" = "/tags.html"
"/as.html" = "/intro_to_programming/setup.html"
"/git.html" = "/intro_to_programming/intro_to_git.html"
"/jdk.html" = "/gradle/downgrading_gradle_jdk/downgrading_gradle_jdk.html"
"/downgrade.html" = "/gradle/downgrading_gradle_jdk/downgrading_gradle_jdk.html"
"/gradle.html" = "/gradle/dont_upgrade/dont_upgrade.html"
"/emptylist.html" = "/roadrunner_10/null_list_error_in_rr_10.html"
"/builder.html" = "/roadrunner_10/complete_trajectorybuilder_reference.html"
"/bump.html" = "/roadrunner_056/is_the_bump_on_manual_feedforward_tuner_normal.html"
"/ffbump.html" = "/roadrunner_056/is_the_bump_on_manual_feedforward_tuner_normal.html"
"/overshoot.html" = "/roadrunner_056/is_the_bump_on_manual_feedforward_tuner_normal.html"
"/null.html" = "/common_ds_errors/npe_at_init/npe_at_init.html"
"/npe.html" = "/common_ds_errors/npe_at_init/npe_at_init.html"
"/27971.html" = "/common_ds_errors/npe_at_init/npe_at_init.html"
"/pid.html" = "/pidf_controllers/integrating_a_custom_PIDF_controller.html"
"/pidf.html" = "/pidf_controllers/integrating_a_custom_PIDF_controller.html"
"/pidsync.html" = "/pidf_controllers/syncing_two_linear_slide_motors_using_a_pidf_controller/syncing_two_linear_slide_motors_using_a_pidf_controller.html"
"/usb.html" = "/electrical/why_we_should_only_use_usb_30.html"
"/usb3.html" = "/electrical/why_we_should_only_use_usb_30.html"
"/odo.html" = "electrical/how_to_wire_odometry_pods.html"
"/kotlin.html" = "/misc/why_kotlin/why_kotlin.html"
"/loop.html" =  "/improving_loop_times/improving_loop_times.html"
"/looptimes.html" = "/improving_loop_times/improving_loop_times.html"
"/pedrovsrr.html" = "/misc/pedro_vs_roadrunner.html"
"/pedro.html" = "/misc/pedro_vs_roadrunner.html"
"/rrvspedro.html" = "/misc/pedro_vs_roadrunner.html"
"/rrvpedro.html" = "/misc/pedro_vs_roadrunner.html"
"/tab.html" = "/roadrunner_10/complete_trajectorybuilder_reference.html"
"/trajectory.html" = "/roadrunner_10/complete_trajectorybuilder_reference.html"
"/inpertick.html" = "/roadrunner_10/vref_small_v0_high_rr_10.html"
"/tickperin.html" = "/roadrunner_10/vref_small_v0_high_rr_10.html"
"/vref.html" = "/roadrunner_10/vref_small_v0_high_rr_10.html"